name: Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - "closed"
  push:
    branches:
      - "feat/github-workflows" # TO DELETE

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_REGISTRY: "020856120665.dkr.ecr.us-east-1.amazonaws.com/dev-devops-course-ecr"
  TAG: "${{ github.run_number }}.${{ github.run_attempt }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker registry
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}:${{ env.TAG }}
