name: "Release test"

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: test
        run: echo ${{ github.ref_name }}
